# Generated by Django 3.0.6 on 2020-10-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'to_do'), ('WIP', 'in_progress'), ('DONE', 'done'), ('REV', 'review')], default='TO_DO', max_length=20)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources_api.Subject')),
            ],
        ),
    ]
